version: "3.3"

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: gelyamolodets/yamdb
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/ 
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=gelyamolodets.hopto.org
      - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
